name: ultralytics_yolo
description: Flutter plugin for Ultralytics YOLO computer vision models.
version: 0.1.26
homepage: https://github.com/ultralytics/yolo-flutter-app
repository: https://github.com/ultralytics/yolo-flutter-app
issue_tracker: https://github.com/ultralytics/yolo-flutter-app/issues
example: example/example.dart

topics:
  - computer-vision
  - object-detection
  - yolo
  - machine-learning
  - flutter-plugin

funding:
  - https://github.com/sponsors/ultralytics

# Environment configuration
environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.1"

# Dependencies for the Flutter plugin
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

# Development dependencies
dev_dependencies:
  coverage: ^1.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^6.0.0  # Static analysis tool for Flutter code

flutter:
  plugin:
    platforms:
      android:
        package: com.ultralytics.yolo
        pluginClass: YOLOPlugin
      ios:
        pluginClass: YOLOPlugin

  assets:
    - assets/toothie.png  # Image used in the app

# Platform-specific plugin settings (outside flutter:)
platforms:
  android:
    minSdkVersion: 21
    targetSdkVersion: 30
  ios:
    deploymentTarget: '11.0'
